# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5767ff88477e5dc25ef7e5407438617a04c3d0732898c4d812b94ec7ca8f59e1a161dc992acf67421c5e7ea135b3e2708a8d6b3957f75b1f4ad37ff18972cf0c

test:
  secret_key_base: db9e48f452426fa16e7a03b18ddb66eb788a9f239efcffd559a50572df0c4baf4ada22e4c15a8d210c4d14cd59702797a9b95c161ac20d00230e8c195323ed6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
